name: CI
on: 
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .editorconfig
      - .gitignore
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      id: build
      run: wolframscript Build.wls
    - name: Run Tests
      run: wolframscript RunTests.wls
      env:
        PACLET_PATH: ${{ steps.build.outputs.path }}
    - name: Create Release
      if: startsWith(github.event.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
    - name: Upload Release Asset
      if: startsWith(github.event.ref, 'refs/tags/v')
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_REF_NAME: ${{ github.ref }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.build.outputs.name }}
        asset_name: ${{ steps.build.outputs.name }}
        asset_content_type: application/zip
